### ISSUE TITLE
There were unauthenticated packages and -y was used without --allow-unauthenticated

### ISSUE THREAD

**Issue by VertigoRay** [salt-formulas/salt-formula-virtualbox#1]
Got an error:

```
          ID: virtualbox_packages
    Function: pkg.installed
        Name: virtualbox-5.0
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:

              errors:
                  - Running scope as unit: run-r57bf126e0f2c4e218c021dabf6488049.scope
                    E: There were unauthenticated packages and -y was used without --allow-unauthenticated
     Started: 13:44:00.961263
    Duration: 478.793 ms
     Changes:
```

I have to assume this is because the GPG key isn't being installed as part of this formula.

- Distributor ID: Debian
- Description:    Debian GNU/Linux 9.2 (stretch)
- Release:        9.2
- Codename:       stretch
